### ISSUE TITLE
issue-1-user-can-see-single-page-website

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/swetspot#1]
## ✅ Task List

- [x] Create the following files and components `Navbar`, `Banner`, `Services`, `Blog`, `About Us`, `Contact Us` and `Footer`.
- [x] Import the components to the `Home` component.
- [x] Within the `Navbar` component:
  - [x] Add the logo to the left side of the page.
  - [x] Add a `burger` icon to the right side of the page (on phone and tablet).
  - [x] Add the navigation links to the right side of the page (on desktop).
  - [x] Add a `exit` icon to the modal.
  - [x] Add the navigation links to the modal.
  - [x] Make the `burger` icon slide a modal over the page.
- [x] Within the `Banner` component:
  - [x] Add a background to the `Banner` component and make it responsive stretching from each side of the page.
  - [x] Add a `Get Quote` button.
- [x] Within the `Service` component:
  - [x] Create a `Service` title.
  - [x] Create a card for each service.
  - [x] Add a image for each card.
  - [x] Add a `More` link.
- [x] Within the `Blog` component:
  - [x] Create a `Blog` title.
  - [x] Add a `More` link.
- [x] Within the `About Us` component:
  - [x] Create the card components and add the text.
- [x] Within the `Contact Us` component:
  - [x] Create the form and the social link.
- [x] Within the `Partners` component:
  - [x] Add the text.
  - [x] Add the images.
- [x] Within the `Footer` component:
  - [x] Add the text.
- [x] Add links to the 'a' tag to scroll within the page.
- [x] Make the 'Navbar' fixed:
  - [x] Add the bottom white line to the navbar.
  - [x] Make the 'Navbar' fixed as the user is scrolling.
- [x] Fix scrolling bug.
