### ISSUE TITLE
issue-2-user-can-see-service-dropdown-menu

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/swetspot#2]
## ✅ Task List

- [x] Create a `Drobdown` component and import `React` to it. 
- [x] Create a class within `Dropdown` with `constructor` method and a `state` with `dropdown` as its only property. The state `dropdown` property should be set to `false`.
- [x] Import `Drobdown` to `Services`.
- [x] Create a `toggle` method that will set the `state.dropdown` as opposite to the current value.
- [x] Create a list of services to be rendered by the `render` method.
- [x] Within the `render` method, if `state.dropdown` is true, render the list of services. Else, render nothing.
- [x] Clean code.
