### ISSUE TITLE
issue-3-user-can-see-blog-page

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/swetspot#3]
## ✅ Task List

- [x] Create a `BlogPage` component.
- [x] Import `React`, `Navbar` and `Footer` to `BlogPage`.
- [x] Within `BlogPage` create a class and export it.
- [x] Create a new page using `Navbar` and `Footer`.
- [x] Import `BlogPage` to `App`.
- [x] Add the `componentDidMount` method and listen for the `hashchange` event.
- [x] If the new hash starts with `blog-page` render the `BlogPage` component.
- [x] When the `See All` button is clicked open the `BlogPage`.
- [x] Add the tables to `schema.sql`.
- [x] Add the data to `data.sql`.
- [x] Create a `errorMiddleware` function to handle the error.
- [x] Create a `ClientError` class to send the error message to the user.
- [x] Create the `endpoint` to access the database.
- [x] Create a `fetch` request within `BlogPage`.
- [x] Create the `BlogPage` layout.
- [x] Create a `PostPreview` component. Create the function, export it and import it to `BlogPage`.
- [x] Create the `PostPreview` layout.
- [x] `Map` the `PostPreview`.
