### ISSUE TITLE
issue-4-user-can-see-blog-post

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/swetspot#4]
## ✅ Task List

- [x] Add an `a` tag to the `PostPreview`.
- [x] Create the `Post` component. 
- [x] Create the `endpoint` to request the post data.
- [x] Add a `fetch` request to `Post`.
- [x] Create the `Post` layout.
