### ISSUE TITLE
issue-5-user-can-see-blog-posts-previews-on-the-home-page

### ISSUE THREAD

**Issue by luccarizzi** [luccarizzi/swetspot#5]
## ✅ Task List

- [x] Create an `endpoint` to retrieve the data from the database.
- [x] Create a `fetch` requests within `Blog` component.
- [x] Create the layout of blog posts preview.
